/*
NHÓM 4 - HỆ THỐNG QUẢN LÝ BỆNH VIỆN RĂNG HÀM MẶT
Nguồn: YTuongDB_Nhom4_v2(3).docx. Đủ 34 bảng, giữ nguyên các trường chi tiết.
Hệ quản trị: Microsoft SQL Server (T-SQL).
Cách chạy: mở file bằng SQL Server Management Studio, kết nối máy chủ,
chạy toàn bộ script (F5) với tài khoản có quyền tạo database/bảng.
Script tạo database QLBenhVienRangHamMat nếu chưa có; chỉ cài vào database
chưa có bảng người dùng. Nếu đã có bảng, dừng và không xóa dữ liệu.

QUY ƯỚC BỔ SUNG VÌ TÀI LIỆU CHƯA CHỈ ĐỊNH KIỂU DỮ LIỆU:
- Khóa chính INT IDENTITY; khóa ngoại INT; văn bản tiếng Việt NVARCHAR.
- Tiền DECIMAL(18,2), số lượng DECIMAL(18,3); thời điểm DATETIME2(0).
- Trạng thái là NVARCHAR(50), ứng dụng thống nhất bộ giá trị nghiệp vụ.
- MaBS tham chiếu NHAN_VIEN.MaNV; ứng dụng kiểm tra chức vụ bác sĩ.
- NHAN_VIEN.MaChucVu là FK theo bảng quan hệ trong tài liệu.
- Chọn tên TINH_TRANG_BENH theo mục mô tả chi tiết (tổng quan gọi là
  TINH_TRANG_RANG). Không tự thêm trường số răng vì tài liệu chưa liệt kê.
- CHI_TIET_HOA_DON giữ MaKHDT; không thêm MaDV dù bảng quan hệ có nêu
  DICH_VU -> CHI_TIET_HOA_DON, vì danh sách trường chi tiết không có MaDV.
- MatKhau chỉ chứa chuỗi băm mật khẩu có salt do ứng dụng tạo (không lưu
  mật khẩu rõ). Không tạo tài khoản hoặc mật khẩu mẫu.
- ThanhTien hóa đơn = TongTien - GiamGia (GiamGia là số tiền, không phải %).
  Tổng hóa đơn/chi tiết và tổng thanh toán do ứng dụng cập nhật trong transaction.
- GIAO_DICH_KHO.SoLuongLo là biến động có dấu: nhập dương, xuất âm,
  điều chỉnh là chênh lệch. Mọi nhập ban đầu phải có giao dịch dương;
  tồn = SUM(SoLuongLo), KHÔNG cộng thêm LO_VAT_TU.SoLuongNhap lần nữa.
  Ứng dụng kiểm tra tồn âm trong transaction có khóa thích hợp.
- Ngày/giờ lưu theo giờ máy chủ SQL Server; cấu hình thống nhất với ứng dụng.
- PhongSuDung và NguoiThu giữ là văn bản theo thuộc tính trong tài liệu.
- Ứng dụng kiểm tra tính nhất quán bệnh nhân/hồ sơ/lịch/lần khám, chuyên khoa,
  xung đột khoảng giờ, quy trình duyệt nghỉ/thay thế và thanh toán vượt dư nợ.
- Không dùng CASCADE DELETE để tránh xóa dây chuyền dữ liệu nghiệp vụ.
- Không kèm dữ liệu mẫu, trigger hay stored procedure ngoài phạm vi tạo schema.
*/
USE [master];
GO
IF DB_ID(N'QLBenhVienRangHamMat') IS NULL
    EXEC(N'CREATE DATABASE [QLBenhVienRangHamMat]');
GO
USE [QLBenhVienRangHamMat];
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;

BEGIN TRY
    IF EXISTS (SELECT 1 FROM sys.tables WHERE is_ms_shipped = 0)
        THROW 50001, N'Database đã có bảng. Script chỉ dùng khởi tạo database trống.', 1;

    BEGIN TRANSACTION;

-- 01. BENH_NHAN
CREATE TABLE [dbo].[BENH_NHAN] (
    [MaBN] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_BENH_NHAN] PRIMARY KEY,
    [HoTenBN] NVARCHAR(255) NOT NULL,
    [GioiTinh] NVARCHAR(50) NULL,
    [NgaySinh] DATE NULL,
    [SDT] NVARCHAR(50) NULL,
    [DiaChi] NVARCHAR(255) NULL,
    [MaBHYT] NVARCHAR(50) NULL,
    [NhomMau] NVARCHAR(50) NULL,
    [TienSuBenh] NVARCHAR(MAX) NULL,
    [DiUng] NVARCHAR(MAX) NULL,
    [TrangThai] NVARCHAR(50) NOT NULL
);

-- 02. HO_SO_BENH_AN
CREATE TABLE [dbo].[HO_SO_BENH_AN] (
    [MaHS] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_HO_SO_BENH_AN] PRIMARY KEY,
    [MaBN] INT NOT NULL,
    [NgayLap] DATETIME2(0) NOT NULL DEFAULT (SYSDATETIME()),
    [LyDoKhamBanDau] NVARCHAR(MAX) NULL,
    [GhiChu] NVARCHAR(MAX) NULL,
    [TrangThai] NVARCHAR(50) NOT NULL,
    CONSTRAINT [UQ_HO_SO_BENH_AN_MaBN] UNIQUE ([MaBN])
);

-- 03. PHIEU_KHAM_BENH
CREATE TABLE [dbo].[PHIEU_KHAM_BENH] (
    [MaPhieu] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_PHIEU_KHAM_BENH] PRIMARY KEY,
    [MaBN] INT NOT NULL,
    [MaHS] INT NOT NULL,
    [MaLich] INT NULL,
    [MaKhoa] INT NOT NULL,
    [MaPhong] INT NOT NULL,
    [MaBS] INT NULL,
    [MaDV] INT NOT NULL,
    [SoThuTu] INT NOT NULL,
    [ThoiGianTiepNhan] DATETIME2(0) NOT NULL DEFAULT (SYSDATETIME()),
    [LyDoKham] NVARCHAR(MAX) NULL,
    [TrangThai] NVARCHAR(50) NOT NULL,
    [GhiChu] NVARCHAR(MAX) NULL,
    CONSTRAINT [CK_PHIEU_KHAM_BENH_SoThuTu] CHECK ([SoThuTu] > 0)
);

-- 04. LICH_SU_KHAM_BENH
CREATE TABLE [dbo].[LICH_SU_KHAM_BENH] (
    [MaLS] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_LICH_SU_KHAM_BENH] PRIMARY KEY,
    [MaHS] INT NOT NULL,
    [MaLich] INT NULL,
    [ThoiGianKham] DATETIME2(0) NOT NULL DEFAULT (SYSDATETIME()),
    [TrieuChung] NVARCHAR(MAX) NULL,
    [ChanDoan] NVARCHAR(MAX) NULL,
    [KeHoachXuLy] NVARCHAR(MAX) NULL,
    [GhiChu] NVARCHAR(MAX) NULL
);

-- 05. TINH_TRANG_BENH
CREATE TABLE [dbo].[TINH_TRANG_BENH] (
    [MaTTB] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_TINH_TRANG_BENH] PRIMARY KEY,
    [MaLS] INT NOT NULL,
    [TinhTrang] NVARCHAR(255) NOT NULL,
    [ChanDoan] NVARCHAR(MAX) NULL,
    [MucDo] NVARCHAR(255) NULL,
    [GhiChu] NVARCHAR(MAX) NULL
);

-- 06. DON_THUOC
CREATE TABLE [dbo].[DON_THUOC] (
    [MaDT] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_DON_THUOC] PRIMARY KEY,
    [MaLS] INT NOT NULL,
    [MaBS] INT NOT NULL,
    [NgayKe] DATETIME2(0) NOT NULL DEFAULT (SYSDATETIME()),
    [ChanDoan] NVARCHAR(MAX) NULL,
    [GhiChu] NVARCHAR(MAX) NULL
);

-- 07. CHI_TIET_DON_THUOC
CREATE TABLE [dbo].[CHI_TIET_DON_THUOC] (
    [MaCTDT] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_CHI_TIET_DON_THUOC] PRIMARY KEY,
    [MaDT] INT NOT NULL,
    [TenThuoc] NVARCHAR(255) NOT NULL,
    [LieuDung] NVARCHAR(255) NULL,
    [SoLuong] DECIMAL(18,3) NOT NULL,
    [DonViTinh] NVARCHAR(255) NOT NULL,
    [SoNgayDung] INT NOT NULL,
    [HuongDan] NVARCHAR(MAX) NULL,
    CONSTRAINT [CK_CHI_TIET_DON_THUOC_SoLuong] CHECK ([SoLuong] > 0),
    CONSTRAINT [CK_CHI_TIET_DON_THUOC_SoNgayDung] CHECK ([SoNgayDung] > 0)
);

-- 08. DICH_VU
CREATE TABLE [dbo].[DICH_VU] (
    [MaDV] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_DICH_VU] PRIMARY KEY,
    [TenDV] NVARCHAR(255) NOT NULL,
    [MaCK] INT NULL,
    [DonGia] DECIMAL(18,2) NOT NULL,
    [MoTa] NVARCHAR(MAX) NULL,
    [ThoiGianDuKien] INT NOT NULL,
    [TrangThai] NVARCHAR(50) NOT NULL,
    CONSTRAINT [CK_DICH_VU_DonGia] CHECK ([DonGia] >= 0),
    CONSTRAINT [CK_DICH_VU_ThoiGianDuKien] CHECK ([ThoiGianDuKien] > 0)
);

-- 09. VAI_TRO
CREATE TABLE [dbo].[VAI_TRO] (
    [MaVaiTro] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_VAI_TRO] PRIMARY KEY,
    [TenVaiTro] NVARCHAR(255) NOT NULL,
    [MoTa] NVARCHAR(MAX) NULL
);

-- 10. CHUC_VU
CREATE TABLE [dbo].[CHUC_VU] (
    [MaChucVu] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_CHUC_VU] PRIMARY KEY,
    [TenChucVu] NVARCHAR(255) NOT NULL,
    [MoTa] NVARCHAR(MAX) NULL
);

-- 11. TAI_KHOAN
CREATE TABLE [dbo].[TAI_KHOAN] (
    [MaTK] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_TAI_KHOAN] PRIMARY KEY,
    [TenDangNhap] NVARCHAR(100) NOT NULL,
    [MatKhau] NVARCHAR(255) NOT NULL,
    [MaVaiTro] INT NOT NULL,
    [MaNV] INT NOT NULL,
    [TrangThai] NVARCHAR(50) NOT NULL,
    CONSTRAINT [UQ_TAI_KHOAN_TenDangNhap] UNIQUE ([TenDangNhap]),
    CONSTRAINT [UQ_TAI_KHOAN_MaNV] UNIQUE ([MaNV])
);

-- 12. NHAN_VIEN
CREATE TABLE [dbo].[NHAN_VIEN] (
    [MaNV] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_NHAN_VIEN] PRIMARY KEY,
    [HoTen] NVARCHAR(255) NOT NULL,
    [GioiTinh] NVARCHAR(50) NULL,
    [NgaySinh] DATE NULL,
    [SDT] NVARCHAR(50) NULL,
    [DiaChi] NVARCHAR(255) NULL,
    [MaChucVu] INT NOT NULL,
    [MaCK] INT NULL,
    [BangCap] NVARCHAR(255) NULL,
    [ChungChiHanhNghe] NVARCHAR(255) NULL,
    [NgayCapChungChi] DATE NULL,
    [NoiCapChungChi] NVARCHAR(255) NULL,
    [HanChungChi] DATE NULL,
    [NgayVaoLam] DATE NULL,
    [TrangThai] NVARCHAR(50) NOT NULL,
    CONSTRAINT [CK_NHAN_VIEN_ChungChi] CHECK ([HanChungChi] >= [NgayCapChungChi])
);

-- 13. KHOA
CREATE TABLE [dbo].[KHOA] (
    [MaKhoa] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_KHOA] PRIMARY KEY,
    [TenKhoa] NVARCHAR(255) NOT NULL,
    [DienThoai] NVARCHAR(50) NULL,
    [MoTa] NVARCHAR(MAX) NULL,
    [TrangThai] NVARCHAR(50) NOT NULL
);

-- 14. CHUYEN_KHOA
CREATE TABLE [dbo].[CHUYEN_KHOA] (
    [MaCK] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_CHUYEN_KHOA] PRIMARY KEY,
    [MaKhoa] INT NOT NULL,
    [TenCK] NVARCHAR(255) NOT NULL,
    [MoTa] NVARCHAR(MAX) NULL,
    [TrangThai] NVARCHAR(50) NOT NULL
);

-- 15. KE_HOACH_DIEU_TRI
CREATE TABLE [dbo].[KE_HOACH_DIEU_TRI] (
    [MaKHDT] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_KE_HOACH_DIEU_TRI] PRIMARY KEY,
    [MaLS] INT NOT NULL,
    [MaBN] INT NOT NULL,
    [MaBS] INT NOT NULL,
    [NgayLap] DATETIME2(0) NOT NULL DEFAULT (SYSDATETIME()),
    [NgayBatDau] DATE NULL,
    [NgayDuKienKetThuc] DATE NULL,
    [TrangThai] NVARCHAR(50) NOT NULL,
    [GhiChu] NVARCHAR(MAX) NULL,
    CONSTRAINT [CK_KE_HOACH_DIEU_TRI_Ngay] CHECK ([NgayDuKienKetThuc] >= [NgayBatDau])
);

-- 16. CHI_TIET_KE_HOACH
CREATE TABLE [dbo].[CHI_TIET_KE_HOACH] (
    [MaCTKH] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_CHI_TIET_KE_HOACH] PRIMARY KEY,
    [MaKHDT] INT NOT NULL,
    [MaDV] INT NOT NULL,
    [LanThu] INT NOT NULL,
    [DonGia] DECIMAL(18,2) NOT NULL,
    [ThanhTien] DECIMAL(18,2) NOT NULL,
    [TrangThai] NVARCHAR(50) NOT NULL,
    [GhiChu] NVARCHAR(MAX) NULL,
    CONSTRAINT [CK_CHI_TIET_KE_HOACH_LanThu] CHECK ([LanThu] > 0),
    CONSTRAINT [CK_CHI_TIET_KE_HOACH_DonGia] CHECK ([DonGia] >= 0),
    CONSTRAINT [CK_CHI_TIET_KE_HOACH_ThanhTien] CHECK ([ThanhTien] >= 0)
);

-- 17. THIET_BI
CREATE TABLE [dbo].[THIET_BI] (
    [MaTB] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_THIET_BI] PRIMARY KEY,
    [TenTB] NVARCHAR(255) NOT NULL,
    [LoaiTB] NVARCHAR(255) NULL,
    [SoSerial] NVARCHAR(50) NULL,
    [NgayMua] DATE NULL,
    [MaNCC] INT NULL,
    [PhongSuDung] NVARCHAR(255) NULL,
    [SoLuong] DECIMAL(18,3) NOT NULL,
    [TinhTrang] NVARCHAR(255) NOT NULL,
    [NgayBaoHanh] DATE NULL,
    [GhiChu] NVARCHAR(MAX) NULL,
    CONSTRAINT [CK_THIET_BI_SoLuong] CHECK ([SoLuong] > 0)
);

-- 18. BAO_TRI_THIET_BI
CREATE TABLE [dbo].[BAO_TRI_THIET_BI] (
    [MaBT] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_BAO_TRI_THIET_BI] PRIMARY KEY,
    [MaTB] INT NOT NULL,
    [NgayBaoTri] DATE NULL,
    [LoaiBaoTri] NVARCHAR(255) NULL,
    [NoiDung] NVARCHAR(MAX) NOT NULL,
    [ChiPhi] DECIMAL(18,2) NOT NULL,
    [NguoiThucHien] NVARCHAR(255) NULL,
    [NgayBaoTriTiepTheo] DATE NULL,
    [TrangThai] NVARCHAR(50) NOT NULL,
    [GhiChu] NVARCHAR(MAX) NULL,
    CONSTRAINT [CK_BAO_TRI_THIET_BI_ChiPhi] CHECK ([ChiPhi] >= 0)
);

-- 19. NHA_CUNG_CAP
CREATE TABLE [dbo].[NHA_CUNG_CAP] (
    [MaNCC] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_NHA_CUNG_CAP] PRIMARY KEY,
    [TenNCC] NVARCHAR(255) NOT NULL,
    [SDT] NVARCHAR(50) NULL,
    [Email] NVARCHAR(255) NULL,
    [DiaChi] NVARCHAR(255) NULL,
    [NguoiLienHe] NVARCHAR(255) NULL,
    [TrangThai] NVARCHAR(50) NOT NULL
);

-- 20. PHONG_KHAM
CREATE TABLE [dbo].[PHONG_KHAM] (
    [MaPhong] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_PHONG_KHAM] PRIMARY KEY,
    [TenPhong] NVARCHAR(255) NOT NULL,
    [MaCK] INT NULL,
    [TinhTrang] NVARCHAR(255) NOT NULL
);

-- 21. KHO
CREATE TABLE [dbo].[KHO] (
    [MaKho] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_KHO] PRIMARY KEY,
    [TenKho] NVARCHAR(255) NOT NULL,
    [MaNV] INT NOT NULL,
    [LoaiKho] NVARCHAR(255) NULL,
    [TrangThai] NVARCHAR(50) NOT NULL
);

-- 22. VAT_TU
CREATE TABLE [dbo].[VAT_TU] (
    [MaVT] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_VAT_TU] PRIMARY KEY,
    [TenVT] NVARCHAR(255) NOT NULL,
    [DonViTinh] NVARCHAR(255) NOT NULL,
    [MaLVT] INT NOT NULL,
    [MucTonToiThieu] DECIMAL(18,3) NOT NULL,
    [TrangThai] NVARCHAR(50) NOT NULL,
    CONSTRAINT [CK_VAT_TU_MucTonToiThieu] CHECK ([MucTonToiThieu] >= 0)
);

-- 23. LOAI_VAT_TU
CREATE TABLE [dbo].[LOAI_VAT_TU] (
    [MaLVT] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_LOAI_VAT_TU] PRIMARY KEY,
    [TenLVT] NVARCHAR(255) NOT NULL,
    [GhiChu] NVARCHAR(MAX) NULL
);

-- 24. LO_VAT_TU
CREATE TABLE [dbo].[LO_VAT_TU] (
    [MaLo] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_LO_VAT_TU] PRIMARY KEY,
    [MaVT] INT NOT NULL,
    [MaNCC] INT NOT NULL,
    [MaKho] INT NOT NULL,
    [NgayNhap] DATE NOT NULL,
    [HanSuDung] DATE NULL,
    [SoLuongNhap] DECIMAL(18,3) NOT NULL,
    [DonGiaNhap] DECIMAL(18,2) NOT NULL,
    CONSTRAINT [CK_LO_VAT_TU_SoLuongNhap] CHECK ([SoLuongNhap] > 0),
    CONSTRAINT [CK_LO_VAT_TU_DonGiaNhap] CHECK ([DonGiaNhap] >= 0),
    CONSTRAINT [UQ_LO_VAT_TU_MaLo_MaKho] UNIQUE ([MaLo], [MaKho])
);

-- 25. CA_LAM
CREATE TABLE [dbo].[CA_LAM] (
    [MaCa] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_CA_LAM] PRIMARY KEY,
    [GioBatDau] TIME(0) NOT NULL,
    [GioKetThuc] TIME(0) NOT NULL,
    [GhiChu] NVARCHAR(MAX) NULL,
    CONSTRAINT [CK_CA_LAM_Gio] CHECK ([GioBatDau] <> [GioKetThuc])
);

-- 26. LICH_LAM_VIEC
CREATE TABLE [dbo].[LICH_LAM_VIEC] (
    [MaLLV] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_LICH_LAM_VIEC] PRIMARY KEY,
    [MaNV] INT NOT NULL,
    [MaCa] INT NOT NULL,
    [NgayLam] DATE NOT NULL,
    [MaPhong] INT NOT NULL,
    [TrangThai] NVARCHAR(50) NOT NULL,
    CONSTRAINT [UQ_LICH_LAM_VIEC_MaNV_MaCa_NgayLam] UNIQUE ([MaNV], [MaCa], [NgayLam])
);

-- 27. DON_XIN_NGHI
CREATE TABLE [dbo].[DON_XIN_NGHI] (
    [MaDonNghi] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_DON_XIN_NGHI] PRIMARY KEY,
    [MaNV] INT NOT NULL,
    [TuNgay] DATE NOT NULL,
    [DenNgay] DATE NOT NULL,
    [LyDo] NVARCHAR(MAX) NOT NULL,
    [NgayGui] DATETIME2(0) NOT NULL DEFAULT (SYSDATETIME()),
    [TrangThaiDuyet] NVARCHAR(50) NOT NULL,
    [MaNVDuyet] INT NULL,
    [NgayDuyet] DATETIME2(0) NULL,
    [GhiChu] NVARCHAR(MAX) NULL,
    CONSTRAINT [CK_DON_XIN_NGHI_Ngay] CHECK ([DenNgay] >= [TuNgay]),
    CONSTRAINT [CK_DON_XIN_NGHI_Duyet] CHECK (([NgayDuyet] IS NULL AND [MaNVDuyet] IS NULL) OR ([NgayDuyet] IS NOT NULL AND [MaNVDuyet] IS NOT NULL))
);

-- 28. PHAN_CONG_THAY_THE
CREATE TABLE [dbo].[PHAN_CONG_THAY_THE] (
    [MaPCTT] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_PHAN_CONG_THAY_THE] PRIMARY KEY,
    [MaDonNghi] INT NOT NULL,
    [MaLLVGoc] INT NOT NULL,
    [MaNVThayThe] INT NOT NULL,
    [MaLLVThayThe] INT NULL,
    [NgayXuLy] DATETIME2(0) NOT NULL DEFAULT (SYSDATETIME()),
    [TrangThai] NVARCHAR(50) NOT NULL,
    [LyDoThayThe] NVARCHAR(MAX) NULL,
    [GhiChu] NVARCHAR(MAX) NULL,
    CONSTRAINT [CK_PHAN_CONG_THAY_THE_LichKhac] CHECK ([MaLLVThayThe] <> [MaLLVGoc])
);

-- 29. LICH_KHAM
CREATE TABLE [dbo].[LICH_KHAM] (
    [MaLich] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_LICH_KHAM] PRIMARY KEY,
    [MaBN] INT NOT NULL,
    [MaBS] INT NULL,
    [NgayGioKham] DATETIME2(0) NOT NULL,
    [MaPhong] INT NULL,
    [LyDoKham] NVARCHAR(MAX) NULL,
    [MaDV] INT NOT NULL,
    [TrangThai] NVARCHAR(50) NOT NULL,
    [GhiChu] NVARCHAR(MAX) NULL,
    [NgayTao] DATETIME2(0) NOT NULL DEFAULT (SYSDATETIME())
);

-- 30. HOA_DON
CREATE TABLE [dbo].[HOA_DON] (
    [MaHD] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_HOA_DON] PRIMARY KEY,
    [MaBN] INT NOT NULL,
    [MaLS] INT NULL,
    [NgayLap] DATETIME2(0) NOT NULL DEFAULT (SYSDATETIME()),
    [TongTien] DECIMAL(18,2) NOT NULL,
    [GiamGia] DECIMAL(18,2) NOT NULL DEFAULT (0),
    [ThanhTien] DECIMAL(18,2) NOT NULL,
    [TrangThai] NVARCHAR(50) NOT NULL,
    CONSTRAINT [CK_HOA_DON_TongTien] CHECK ([TongTien] >= 0),
    CONSTRAINT [CK_HOA_DON_GiamGia] CHECK ([GiamGia] >= 0),
    CONSTRAINT [CK_HOA_DON_ThanhTien] CHECK ([ThanhTien] >= 0),
    CONSTRAINT [CK_HOA_DON_TinhTien] CHECK ([GiamGia] <= [TongTien] AND [ThanhTien] = [TongTien] - [GiamGia])
);

-- 31. CHI_TIET_HOA_DON
CREATE TABLE [dbo].[CHI_TIET_HOA_DON] (
    [MaCTHD] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_CHI_TIET_HOA_DON] PRIMARY KEY,
    [MaHD] INT NOT NULL,
    [MaKHDT] INT NULL,
    [NoiDung] NVARCHAR(MAX) NOT NULL,
    [ThanhTien] DECIMAL(18,2) NOT NULL,
    CONSTRAINT [CK_CHI_TIET_HOA_DON_ThanhTien] CHECK ([ThanhTien] >= 0)
);

-- 32. THANH_TOAN
CREATE TABLE [dbo].[THANH_TOAN] (
    [MaTT] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_THANH_TOAN] PRIMARY KEY,
    [MaHD] INT NOT NULL,
    [NgayThanhToan] DATETIME2(0) NOT NULL DEFAULT (SYSDATETIME()),
    [SoTien] DECIMAL(18,2) NOT NULL,
    [PhuongThuc] NVARCHAR(255) NOT NULL,
    [NguoiThu] NVARCHAR(255) NULL,
    [GhiChu] NVARCHAR(MAX) NULL,
    CONSTRAINT [CK_THANH_TOAN_SoTien] CHECK ([SoTien] > 0)
);

-- 33. GIAO_DICH_KHO
CREATE TABLE [dbo].[GIAO_DICH_KHO] (
    [MaGD] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_GIAO_DICH_KHO] PRIMARY KEY,
    [MaLo] INT NOT NULL,
    [MaKho] INT NOT NULL,
    [NgayGD] DATETIME2(0) NOT NULL DEFAULT (SYSDATETIME()),
    [SoLuongLo] DECIMAL(18,3) NOT NULL,
    [LyDo] NVARCHAR(MAX) NOT NULL,
    [GhiChu] NVARCHAR(MAX) NULL,
    CONSTRAINT [CK_GIAO_DICH_KHO_SoLuongLo] CHECK ([SoLuongLo] <> 0)
);

-- 34. HOA_DON_KHO
CREATE TABLE [dbo].[HOA_DON_KHO] (
    [MaHDK] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_HOA_DON_KHO] PRIMARY KEY,
    [MaGD] INT NOT NULL,
    [PhuongThucThanhToan] NVARCHAR(255) NOT NULL,
    [DonGia] DECIMAL(18,2) NOT NULL,
    [ThanhTien] DECIMAL(18,2) NOT NULL,
    [NgayLap] DATETIME2(0) NOT NULL DEFAULT (SYSDATETIME()),
    CONSTRAINT [CK_HOA_DON_KHO_DonGia] CHECK ([DonGia] >= 0),
    CONSTRAINT [CK_HOA_DON_KHO_ThanhTien] CHECK ([ThanhTien] >= 0),
    CONSTRAINT [UQ_HOA_DON_KHO_MaGD] UNIQUE ([MaGD])
);

-- Khóa ngoại: tạo sau khi tất cả bảng đã tồn tại.
ALTER TABLE [dbo].[HO_SO_BENH_AN] ADD CONSTRAINT [FK_HO_SO_BENH_AN_MaBN] FOREIGN KEY ([MaBN]) REFERENCES [dbo].[BENH_NHAN] ([MaBN]);
ALTER TABLE [dbo].[PHIEU_KHAM_BENH] ADD CONSTRAINT [FK_PHIEU_KHAM_BENH_MaBN] FOREIGN KEY ([MaBN]) REFERENCES [dbo].[BENH_NHAN] ([MaBN]);
ALTER TABLE [dbo].[PHIEU_KHAM_BENH] ADD CONSTRAINT [FK_PHIEU_KHAM_BENH_MaHS] FOREIGN KEY ([MaHS]) REFERENCES [dbo].[HO_SO_BENH_AN] ([MaHS]);
ALTER TABLE [dbo].[PHIEU_KHAM_BENH] ADD CONSTRAINT [FK_PHIEU_KHAM_BENH_MaLich] FOREIGN KEY ([MaLich]) REFERENCES [dbo].[LICH_KHAM] ([MaLich]);
ALTER TABLE [dbo].[PHIEU_KHAM_BENH] ADD CONSTRAINT [FK_PHIEU_KHAM_BENH_MaKhoa] FOREIGN KEY ([MaKhoa]) REFERENCES [dbo].[KHOA] ([MaKhoa]);
ALTER TABLE [dbo].[PHIEU_KHAM_BENH] ADD CONSTRAINT [FK_PHIEU_KHAM_BENH_MaPhong] FOREIGN KEY ([MaPhong]) REFERENCES [dbo].[PHONG_KHAM] ([MaPhong]);
ALTER TABLE [dbo].[PHIEU_KHAM_BENH] ADD CONSTRAINT [FK_PHIEU_KHAM_BENH_MaBS] FOREIGN KEY ([MaBS]) REFERENCES [dbo].[NHAN_VIEN] ([MaNV]);
ALTER TABLE [dbo].[PHIEU_KHAM_BENH] ADD CONSTRAINT [FK_PHIEU_KHAM_BENH_MaDV] FOREIGN KEY ([MaDV]) REFERENCES [dbo].[DICH_VU] ([MaDV]);
ALTER TABLE [dbo].[LICH_SU_KHAM_BENH] ADD CONSTRAINT [FK_LICH_SU_KHAM_BENH_MaHS] FOREIGN KEY ([MaHS]) REFERENCES [dbo].[HO_SO_BENH_AN] ([MaHS]);
ALTER TABLE [dbo].[LICH_SU_KHAM_BENH] ADD CONSTRAINT [FK_LICH_SU_KHAM_BENH_MaLich] FOREIGN KEY ([MaLich]) REFERENCES [dbo].[LICH_KHAM] ([MaLich]);
ALTER TABLE [dbo].[TINH_TRANG_BENH] ADD CONSTRAINT [FK_TINH_TRANG_BENH_MaLS] FOREIGN KEY ([MaLS]) REFERENCES [dbo].[LICH_SU_KHAM_BENH] ([MaLS]);
ALTER TABLE [dbo].[DON_THUOC] ADD CONSTRAINT [FK_DON_THUOC_MaLS] FOREIGN KEY ([MaLS]) REFERENCES [dbo].[LICH_SU_KHAM_BENH] ([MaLS]);
ALTER TABLE [dbo].[DON_THUOC] ADD CONSTRAINT [FK_DON_THUOC_MaBS] FOREIGN KEY ([MaBS]) REFERENCES [dbo].[NHAN_VIEN] ([MaNV]);
ALTER TABLE [dbo].[CHI_TIET_DON_THUOC] ADD CONSTRAINT [FK_CHI_TIET_DON_THUOC_MaDT] FOREIGN KEY ([MaDT]) REFERENCES [dbo].[DON_THUOC] ([MaDT]);
ALTER TABLE [dbo].[DICH_VU] ADD CONSTRAINT [FK_DICH_VU_MaCK] FOREIGN KEY ([MaCK]) REFERENCES [dbo].[CHUYEN_KHOA] ([MaCK]);
ALTER TABLE [dbo].[TAI_KHOAN] ADD CONSTRAINT [FK_TAI_KHOAN_MaVaiTro] FOREIGN KEY ([MaVaiTro]) REFERENCES [dbo].[VAI_TRO] ([MaVaiTro]);
ALTER TABLE [dbo].[TAI_KHOAN] ADD CONSTRAINT [FK_TAI_KHOAN_MaNV] FOREIGN KEY ([MaNV]) REFERENCES [dbo].[NHAN_VIEN] ([MaNV]);
ALTER TABLE [dbo].[NHAN_VIEN] ADD CONSTRAINT [FK_NHAN_VIEN_MaChucVu] FOREIGN KEY ([MaChucVu]) REFERENCES [dbo].[CHUC_VU] ([MaChucVu]);
ALTER TABLE [dbo].[NHAN_VIEN] ADD CONSTRAINT [FK_NHAN_VIEN_MaCK] FOREIGN KEY ([MaCK]) REFERENCES [dbo].[CHUYEN_KHOA] ([MaCK]);
ALTER TABLE [dbo].[CHUYEN_KHOA] ADD CONSTRAINT [FK_CHUYEN_KHOA_MaKhoa] FOREIGN KEY ([MaKhoa]) REFERENCES [dbo].[KHOA] ([MaKhoa]);
ALTER TABLE [dbo].[KE_HOACH_DIEU_TRI] ADD CONSTRAINT [FK_KE_HOACH_DIEU_TRI_MaLS] FOREIGN KEY ([MaLS]) REFERENCES [dbo].[LICH_SU_KHAM_BENH] ([MaLS]);
ALTER TABLE [dbo].[KE_HOACH_DIEU_TRI] ADD CONSTRAINT [FK_KE_HOACH_DIEU_TRI_MaBN] FOREIGN KEY ([MaBN]) REFERENCES [dbo].[BENH_NHAN] ([MaBN]);
ALTER TABLE [dbo].[KE_HOACH_DIEU_TRI] ADD CONSTRAINT [FK_KE_HOACH_DIEU_TRI_MaBS] FOREIGN KEY ([MaBS]) REFERENCES [dbo].[NHAN_VIEN] ([MaNV]);
ALTER TABLE [dbo].[CHI_TIET_KE_HOACH] ADD CONSTRAINT [FK_CHI_TIET_KE_HOACH_MaKHDT] FOREIGN KEY ([MaKHDT]) REFERENCES [dbo].[KE_HOACH_DIEU_TRI] ([MaKHDT]);
ALTER TABLE [dbo].[CHI_TIET_KE_HOACH] ADD CONSTRAINT [FK_CHI_TIET_KE_HOACH_MaDV] FOREIGN KEY ([MaDV]) REFERENCES [dbo].[DICH_VU] ([MaDV]);
ALTER TABLE [dbo].[THIET_BI] ADD CONSTRAINT [FK_THIET_BI_MaNCC] FOREIGN KEY ([MaNCC]) REFERENCES [dbo].[NHA_CUNG_CAP] ([MaNCC]);
ALTER TABLE [dbo].[BAO_TRI_THIET_BI] ADD CONSTRAINT [FK_BAO_TRI_THIET_BI_MaTB] FOREIGN KEY ([MaTB]) REFERENCES [dbo].[THIET_BI] ([MaTB]);
ALTER TABLE [dbo].[PHONG_KHAM] ADD CONSTRAINT [FK_PHONG_KHAM_MaCK] FOREIGN KEY ([MaCK]) REFERENCES [dbo].[CHUYEN_KHOA] ([MaCK]);
ALTER TABLE [dbo].[KHO] ADD CONSTRAINT [FK_KHO_MaNV] FOREIGN KEY ([MaNV]) REFERENCES [dbo].[NHAN_VIEN] ([MaNV]);
ALTER TABLE [dbo].[VAT_TU] ADD CONSTRAINT [FK_VAT_TU_MaLVT] FOREIGN KEY ([MaLVT]) REFERENCES [dbo].[LOAI_VAT_TU] ([MaLVT]);
ALTER TABLE [dbo].[LO_VAT_TU] ADD CONSTRAINT [FK_LO_VAT_TU_MaVT] FOREIGN KEY ([MaVT]) REFERENCES [dbo].[VAT_TU] ([MaVT]);
ALTER TABLE [dbo].[LO_VAT_TU] ADD CONSTRAINT [FK_LO_VAT_TU_MaNCC] FOREIGN KEY ([MaNCC]) REFERENCES [dbo].[NHA_CUNG_CAP] ([MaNCC]);
ALTER TABLE [dbo].[LO_VAT_TU] ADD CONSTRAINT [FK_LO_VAT_TU_MaKho] FOREIGN KEY ([MaKho]) REFERENCES [dbo].[KHO] ([MaKho]);
ALTER TABLE [dbo].[LICH_LAM_VIEC] ADD CONSTRAINT [FK_LICH_LAM_VIEC_MaNV] FOREIGN KEY ([MaNV]) REFERENCES [dbo].[NHAN_VIEN] ([MaNV]);
ALTER TABLE [dbo].[LICH_LAM_VIEC] ADD CONSTRAINT [FK_LICH_LAM_VIEC_MaCa] FOREIGN KEY ([MaCa]) REFERENCES [dbo].[CA_LAM] ([MaCa]);
ALTER TABLE [dbo].[LICH_LAM_VIEC] ADD CONSTRAINT [FK_LICH_LAM_VIEC_MaPhong] FOREIGN KEY ([MaPhong]) REFERENCES [dbo].[PHONG_KHAM] ([MaPhong]);
ALTER TABLE [dbo].[DON_XIN_NGHI] ADD CONSTRAINT [FK_DON_XIN_NGHI_MaNV] FOREIGN KEY ([MaNV]) REFERENCES [dbo].[NHAN_VIEN] ([MaNV]);
ALTER TABLE [dbo].[DON_XIN_NGHI] ADD CONSTRAINT [FK_DON_XIN_NGHI_MaNVDuyet] FOREIGN KEY ([MaNVDuyet]) REFERENCES [dbo].[NHAN_VIEN] ([MaNV]);
ALTER TABLE [dbo].[PHAN_CONG_THAY_THE] ADD CONSTRAINT [FK_PHAN_CONG_THAY_THE_MaDonNghi] FOREIGN KEY ([MaDonNghi]) REFERENCES [dbo].[DON_XIN_NGHI] ([MaDonNghi]);
ALTER TABLE [dbo].[PHAN_CONG_THAY_THE] ADD CONSTRAINT [FK_PHAN_CONG_THAY_THE_MaLLVGoc] FOREIGN KEY ([MaLLVGoc]) REFERENCES [dbo].[LICH_LAM_VIEC] ([MaLLV]);
ALTER TABLE [dbo].[PHAN_CONG_THAY_THE] ADD CONSTRAINT [FK_PHAN_CONG_THAY_THE_MaNVThayThe] FOREIGN KEY ([MaNVThayThe]) REFERENCES [dbo].[NHAN_VIEN] ([MaNV]);
ALTER TABLE [dbo].[PHAN_CONG_THAY_THE] ADD CONSTRAINT [FK_PHAN_CONG_THAY_THE_MaLLVThayThe] FOREIGN KEY ([MaLLVThayThe]) REFERENCES [dbo].[LICH_LAM_VIEC] ([MaLLV]);
ALTER TABLE [dbo].[LICH_KHAM] ADD CONSTRAINT [FK_LICH_KHAM_MaBN] FOREIGN KEY ([MaBN]) REFERENCES [dbo].[BENH_NHAN] ([MaBN]);
ALTER TABLE [dbo].[LICH_KHAM] ADD CONSTRAINT [FK_LICH_KHAM_MaBS] FOREIGN KEY ([MaBS]) REFERENCES [dbo].[NHAN_VIEN] ([MaNV]);
ALTER TABLE [dbo].[LICH_KHAM] ADD CONSTRAINT [FK_LICH_KHAM_MaPhong] FOREIGN KEY ([MaPhong]) REFERENCES [dbo].[PHONG_KHAM] ([MaPhong]);
ALTER TABLE [dbo].[LICH_KHAM] ADD CONSTRAINT [FK_LICH_KHAM_MaDV] FOREIGN KEY ([MaDV]) REFERENCES [dbo].[DICH_VU] ([MaDV]);
ALTER TABLE [dbo].[HOA_DON] ADD CONSTRAINT [FK_HOA_DON_MaBN] FOREIGN KEY ([MaBN]) REFERENCES [dbo].[BENH_NHAN] ([MaBN]);
ALTER TABLE [dbo].[HOA_DON] ADD CONSTRAINT [FK_HOA_DON_MaLS] FOREIGN KEY ([MaLS]) REFERENCES [dbo].[LICH_SU_KHAM_BENH] ([MaLS]);
ALTER TABLE [dbo].[CHI_TIET_HOA_DON] ADD CONSTRAINT [FK_CHI_TIET_HOA_DON_MaHD] FOREIGN KEY ([MaHD]) REFERENCES [dbo].[HOA_DON] ([MaHD]);
ALTER TABLE [dbo].[CHI_TIET_HOA_DON] ADD CONSTRAINT [FK_CHI_TIET_HOA_DON_MaKHDT] FOREIGN KEY ([MaKHDT]) REFERENCES [dbo].[KE_HOACH_DIEU_TRI] ([MaKHDT]);
ALTER TABLE [dbo].[THANH_TOAN] ADD CONSTRAINT [FK_THANH_TOAN_MaHD] FOREIGN KEY ([MaHD]) REFERENCES [dbo].[HOA_DON] ([MaHD]);
ALTER TABLE [dbo].[GIAO_DICH_KHO] ADD CONSTRAINT [FK_GIAO_DICH_KHO_MaLo] FOREIGN KEY ([MaLo]) REFERENCES [dbo].[LO_VAT_TU] ([MaLo]);
ALTER TABLE [dbo].[GIAO_DICH_KHO] ADD CONSTRAINT [FK_GIAO_DICH_KHO_MaKho] FOREIGN KEY ([MaKho]) REFERENCES [dbo].[KHO] ([MaKho]);
ALTER TABLE [dbo].[HOA_DON_KHO] ADD CONSTRAINT [FK_HOA_DON_KHO_MaGD] FOREIGN KEY ([MaGD]) REFERENCES [dbo].[GIAO_DICH_KHO] ([MaGD]);

-- Bảo đảm kho của giao dịch chính là kho đang giữ lô.
ALTER TABLE [dbo].[GIAO_DICH_KHO] ADD CONSTRAINT [FK_GIAO_DICH_KHO_LoKho]
    FOREIGN KEY ([MaLo], [MaKho]) REFERENCES [dbo].[LO_VAT_TU] ([MaLo], [MaKho]);
-- Lịch hẹn chỉ được lập tối đa một phiếu; bệnh nhân vãng lai có MaLich NULL.
CREATE UNIQUE INDEX [UX_PHIEU_KHAM_BENH_MaLich]
    ON [dbo].[PHIEU_KHAM_BENH] ([MaLich]) WHERE [MaLich] IS NOT NULL;

-- Chỉ mục hỗ trợ tra cứu các liên kết nghiệp vụ.
CREATE INDEX [IX_PHIEU_KHAM_BENH_MaBN] ON [dbo].[PHIEU_KHAM_BENH] ([MaBN]);
CREATE INDEX [IX_PHIEU_KHAM_BENH_MaHS] ON [dbo].[PHIEU_KHAM_BENH] ([MaHS]);
CREATE INDEX [IX_PHIEU_KHAM_BENH_MaKhoa] ON [dbo].[PHIEU_KHAM_BENH] ([MaKhoa]);
CREATE INDEX [IX_PHIEU_KHAM_BENH_MaPhong] ON [dbo].[PHIEU_KHAM_BENH] ([MaPhong]);
CREATE INDEX [IX_PHIEU_KHAM_BENH_MaBS] ON [dbo].[PHIEU_KHAM_BENH] ([MaBS]);
CREATE INDEX [IX_PHIEU_KHAM_BENH_MaDV] ON [dbo].[PHIEU_KHAM_BENH] ([MaDV]);
CREATE INDEX [IX_LICH_SU_KHAM_BENH_MaHS] ON [dbo].[LICH_SU_KHAM_BENH] ([MaHS]);
CREATE INDEX [IX_LICH_SU_KHAM_BENH_MaLich] ON [dbo].[LICH_SU_KHAM_BENH] ([MaLich]);
CREATE INDEX [IX_TINH_TRANG_BENH_MaLS] ON [dbo].[TINH_TRANG_BENH] ([MaLS]);
CREATE INDEX [IX_DON_THUOC_MaLS] ON [dbo].[DON_THUOC] ([MaLS]);
CREATE INDEX [IX_DON_THUOC_MaBS] ON [dbo].[DON_THUOC] ([MaBS]);
CREATE INDEX [IX_CHI_TIET_DON_THUOC_MaDT] ON [dbo].[CHI_TIET_DON_THUOC] ([MaDT]);
CREATE INDEX [IX_DICH_VU_MaCK] ON [dbo].[DICH_VU] ([MaCK]);
CREATE INDEX [IX_TAI_KHOAN_MaVaiTro] ON [dbo].[TAI_KHOAN] ([MaVaiTro]);
CREATE INDEX [IX_NHAN_VIEN_MaChucVu] ON [dbo].[NHAN_VIEN] ([MaChucVu]);
CREATE INDEX [IX_NHAN_VIEN_MaCK] ON [dbo].[NHAN_VIEN] ([MaCK]);
CREATE INDEX [IX_CHUYEN_KHOA_MaKhoa] ON [dbo].[CHUYEN_KHOA] ([MaKhoa]);
CREATE INDEX [IX_KE_HOACH_DIEU_TRI_MaLS] ON [dbo].[KE_HOACH_DIEU_TRI] ([MaLS]);
CREATE INDEX [IX_KE_HOACH_DIEU_TRI_MaBN] ON [dbo].[KE_HOACH_DIEU_TRI] ([MaBN]);
CREATE INDEX [IX_KE_HOACH_DIEU_TRI_MaBS] ON [dbo].[KE_HOACH_DIEU_TRI] ([MaBS]);
CREATE INDEX [IX_CHI_TIET_KE_HOACH_MaKHDT] ON [dbo].[CHI_TIET_KE_HOACH] ([MaKHDT]);
CREATE INDEX [IX_CHI_TIET_KE_HOACH_MaDV] ON [dbo].[CHI_TIET_KE_HOACH] ([MaDV]);
CREATE INDEX [IX_THIET_BI_MaNCC] ON [dbo].[THIET_BI] ([MaNCC]);
CREATE INDEX [IX_BAO_TRI_THIET_BI_MaTB] ON [dbo].[BAO_TRI_THIET_BI] ([MaTB]);
CREATE INDEX [IX_PHONG_KHAM_MaCK] ON [dbo].[PHONG_KHAM] ([MaCK]);
CREATE INDEX [IX_KHO_MaNV] ON [dbo].[KHO] ([MaNV]);
CREATE INDEX [IX_VAT_TU_MaLVT] ON [dbo].[VAT_TU] ([MaLVT]);
CREATE INDEX [IX_LO_VAT_TU_MaVT] ON [dbo].[LO_VAT_TU] ([MaVT]);
CREATE INDEX [IX_LO_VAT_TU_MaNCC] ON [dbo].[LO_VAT_TU] ([MaNCC]);
CREATE INDEX [IX_LO_VAT_TU_MaKho] ON [dbo].[LO_VAT_TU] ([MaKho]);
CREATE INDEX [IX_LICH_LAM_VIEC_MaCa] ON [dbo].[LICH_LAM_VIEC] ([MaCa]);
CREATE INDEX [IX_LICH_LAM_VIEC_MaPhong] ON [dbo].[LICH_LAM_VIEC] ([MaPhong]);
CREATE INDEX [IX_DON_XIN_NGHI_MaNV] ON [dbo].[DON_XIN_NGHI] ([MaNV]);
CREATE INDEX [IX_DON_XIN_NGHI_MaNVDuyet] ON [dbo].[DON_XIN_NGHI] ([MaNVDuyet]);
CREATE INDEX [IX_PHAN_CONG_THAY_THE_MaDonNghi] ON [dbo].[PHAN_CONG_THAY_THE] ([MaDonNghi]);
CREATE INDEX [IX_PHAN_CONG_THAY_THE_MaLLVGoc] ON [dbo].[PHAN_CONG_THAY_THE] ([MaLLVGoc]);
CREATE INDEX [IX_PHAN_CONG_THAY_THE_MaNVThayThe] ON [dbo].[PHAN_CONG_THAY_THE] ([MaNVThayThe]);
CREATE INDEX [IX_PHAN_CONG_THAY_THE_MaLLVThayThe] ON [dbo].[PHAN_CONG_THAY_THE] ([MaLLVThayThe]);
CREATE INDEX [IX_LICH_KHAM_MaBN] ON [dbo].[LICH_KHAM] ([MaBN]);
CREATE INDEX [IX_LICH_KHAM_MaBS] ON [dbo].[LICH_KHAM] ([MaBS]);
CREATE INDEX [IX_LICH_KHAM_MaPhong] ON [dbo].[LICH_KHAM] ([MaPhong]);
CREATE INDEX [IX_LICH_KHAM_MaDV] ON [dbo].[LICH_KHAM] ([MaDV]);
CREATE INDEX [IX_HOA_DON_MaBN] ON [dbo].[HOA_DON] ([MaBN]);
CREATE INDEX [IX_HOA_DON_MaLS] ON [dbo].[HOA_DON] ([MaLS]);
CREATE INDEX [IX_CHI_TIET_HOA_DON_MaHD] ON [dbo].[CHI_TIET_HOA_DON] ([MaHD]);
CREATE INDEX [IX_CHI_TIET_HOA_DON_MaKHDT] ON [dbo].[CHI_TIET_HOA_DON] ([MaKHDT]);
CREATE INDEX [IX_THANH_TOAN_MaHD] ON [dbo].[THANH_TOAN] ([MaHD]);
CREATE INDEX [IX_GIAO_DICH_KHO_MaLo] ON [dbo].[GIAO_DICH_KHO] ([MaLo]);
CREATE INDEX [IX_GIAO_DICH_KHO_MaKho] ON [dbo].[GIAO_DICH_KHO] ([MaKho]);

    COMMIT TRANSACTION;
    PRINT N'Đã tạo thành công 34 bảng và các ràng buộc.';
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
-- Kiểm tra sau khi chạy: kết quả phải có đủ 34 bảng của thiết kế.
SELECT t.name AS TenBang, COUNT(c.column_id) AS SoCot
FROM sys.tables AS t
JOIN sys.columns AS c ON c.object_id = t.object_id
WHERE t.schema_id = SCHEMA_ID(N'dbo') AND t.is_ms_shipped = 0
GROUP BY t.name
ORDER BY t.name;
GO
